import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth/next";
import SessionProvider from "@/libs/SessionProvider";
import Head from "next/head";

const SS3 = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Ludwik's cpanel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <Head>
        <script
          defer
          data-domain="ludwikfaron.com"
          src="https://plausible.io/js/script.js"
        ></script>
      </Head>
      <body className={SS3.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
