import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { getServerSession } from "next-auth/next";
import { redirect } from "next/navigation";
import Navbar from "../components/Navbar";
import UserProfile from "../components/UserProfile";
import { authOptions } from "../api/auth/[...nextauth]/route";
import Head from "next/head";

const SS3 = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Ludwik's cpanel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (!session) {
    redirect("/");
  }

  if (session.user.role != "admin") {
    redirect("/playground");
  }

  return (
    <main className={SS3.className}>
      <Head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-NVFL8C3ZCT');
            `,
          }}
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-NVFL8C3ZCT"
        />
      </Head>
      <UserProfile />
      <Navbar />
      {children}
    </main>
  );
}
